//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealNews.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RealNews.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] notfound {
            get {
                object obj = ResourceManager.GetObject("notfound", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html dir=&quot;rtl&quot;&gt;
        ///&lt;script src=&quot;badcode.js&quot;&gt;&lt;/script&gt;
        ///&lt;IMG SRC=&quot;javascript:alert(&apos;XSS&apos;);&quot;&gt;
        ///&lt;img width=&quot;150&quot; height=&quot;150&quot; src=&quot;https://downloadly.ir/wp-content/uploads/2014/04/Alcohol-120-Percent-150x150.png&quot; class=&quot;webfeedsFeaturedVisual wp-post-image&quot; alt=&quot;Alcohol 120 Percent&quot; style=&quot;display: block; margin-bottom: 5px; clear:both;max-width: 100%;&quot; srcset=&quot;https://downloadly.ir/wp-content/uploads/2014/04/Alcohol-120-Percent-150x150.png 150w, https://downloadly.ir/wp-content/uploads/2014/04/Alcohol-120-Perc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What goes into a Docker stack? Carl and Richard talk to Rob Richardson about how containers are evolving in the .NET world. Rob talks about how the Windows side of Docker is actually getting stronger - most developers using Docker use Linux as the template OS. The conversation focuses on moving existing .NET applications into Docker - aka, without .NET Core. It&apos;s certainly possible, and you get some of the container advantages. But with containers comes new thinking around architecture, the ability to organ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As the maker of Windows, Office, and Xbox, Microsoft is undoubtedly against software piracy. When people pirate its games and other software, it arguably takes money out of the companyâ€™s pockets. Believe it or not though, Microsoft is actually promoting piracy! No, not software piracy, but traditional piracy, like with actual pirates. Well, the historical/make-believe type at least. You know, peg legs, eye patches, parrots and such. You see, today it announces theآ Xbox One S Sea Of Thieves Bundle. &quot;As we [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .title{
        ///    background-color: lavender;
        ///    padding: 10px;
        ///    margin-bottom: 15px;
        ///}
        ///
        ///.title h2 {
        ///    font-family: Tahoma;
        ///    font-weight: normal;
        ///}
        ///
        ///.title h2 a {
        ///    text-decoration: none;
        ///}
        ///
        ///.title label{
        ///    margin-left: 5px;
        ///    margin-right: 5px;
        ///}.
        /// </summary>
        internal static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
    }
}
